server {
    listen 80;

    location /health {
        default_type application/json;
        return 200 '{"status":"ok","services":["dockerhub","ghcr","gcpar","verdaccio"]}';
    }

    location /health/dockerhub {
        proxy_pass http://registry-dockerhub:5000/v2/;
    }

    location /health/ghcr {
        proxy_pass http://registry-ghcr:5000/v2/;
    }

    location /health/gcpar {
        proxy_pass http://registry-gcpar:5000/v2/;
    }

    location /health/npm {
        proxy_pass http://verdaccio:4873/-/ping;
    }
}
