ALTER TABLE "build"."git_host_provider" DROP CONSTRAINT "build_git_host_provider_type_valid";--> statement-breakpoint
ALTER TABLE "build"."pipeline_run" DROP CONSTRAINT "build_pipeline_run_status_valid";--> statement-breakpoint
ALTER TABLE "build"."work_item" DROP CONSTRAINT "build_work_item_type_valid";--> statement-breakpoint
ALTER TABLE "build"."work_tracker_provider" DROP CONSTRAINT "build_work_tracker_provider_type_valid";--> statement-breakpoint
ALTER TABLE "commerce"."plan" DROP CONSTRAINT "commerce_plan_type_valid";--> statement-breakpoint
ALTER TABLE "org"."agent" DROP CONSTRAINT "org_agent_status_valid";--> statement-breakpoint
ALTER TABLE "org"."agent" DROP CONSTRAINT "org_agent_type_valid";--> statement-breakpoint
ALTER TABLE "org"."channel" DROP CONSTRAINT "org_channel_kind_valid";--> statement-breakpoint
ALTER TABLE "org"."channel" DROP CONSTRAINT "org_channel_status_valid";--> statement-breakpoint
ALTER TABLE "org"."config_var" DROP CONSTRAINT "org_config_var_scope_type_valid";--> statement-breakpoint
ALTER TABLE "org"."entity_relationship" DROP CONSTRAINT "org_entity_rel_type_valid";--> statement-breakpoint
ALTER TABLE "org"."event_outbox" DROP CONSTRAINT "org_event_outbox_status_valid";--> statement-breakpoint
ALTER TABLE "org"."identity_link" DROP CONSTRAINT "org_identity_link_type_valid";--> statement-breakpoint
ALTER TABLE "org"."job" DROP CONSTRAINT "org_job_status_valid";--> statement-breakpoint
ALTER TABLE "org"."job" DROP CONSTRAINT "org_job_mode_valid";--> statement-breakpoint
ALTER TABLE "org"."job" DROP CONSTRAINT "org_job_trigger_valid";--> statement-breakpoint
ALTER TABLE "org"."memory" DROP CONSTRAINT "org_memory_type_valid";--> statement-breakpoint
ALTER TABLE "org"."memory" DROP CONSTRAINT "org_memory_layer_valid";--> statement-breakpoint
ALTER TABLE "org"."memory" DROP CONSTRAINT "org_memory_status_valid";--> statement-breakpoint
ALTER TABLE "org"."messaging_provider" DROP CONSTRAINT "org_messaging_provider_type_valid";--> statement-breakpoint
ALTER TABLE "org"."principal" DROP CONSTRAINT "org_principal_type_valid";--> statement-breakpoint
ALTER TABLE "org"."scope" DROP CONSTRAINT "org_scope_type_valid";--> statement-breakpoint
ALTER TABLE "org"."secret" DROP CONSTRAINT "org_secret_scope_type_valid";--> statement-breakpoint
ALTER TABLE "org"."ssh_key" DROP CONSTRAINT "org_ssh_key_type_valid";--> statement-breakpoint
ALTER TABLE "org"."team" DROP CONSTRAINT "org_team_type_valid";--> statement-breakpoint
ALTER TABLE "org"."thread" DROP CONSTRAINT "org_thread_type_valid";--> statement-breakpoint
ALTER TABLE "org"."thread" DROP CONSTRAINT "org_thread_source_valid";--> statement-breakpoint
ALTER TABLE "org"."thread" DROP CONSTRAINT "org_thread_status_valid";--> statement-breakpoint
ALTER TABLE "org"."thread_channel" DROP CONSTRAINT "org_thread_channel_role_valid";--> statement-breakpoint
ALTER TABLE "org"."thread_channel" DROP CONSTRAINT "org_thread_channel_status_valid";--> statement-breakpoint
ALTER TABLE "org"."thread_participant" DROP CONSTRAINT "org_thread_participant_role_valid";--> statement-breakpoint
ALTER TABLE "org"."thread_turn" DROP CONSTRAINT "org_thread_turn_role_valid";--> statement-breakpoint
ALTER TABLE "software"."artifact" DROP CONSTRAINT "software_artifact_type_valid";--> statement-breakpoint
ALTER TABLE "software"."capability" DROP CONSTRAINT "software_capability_type_valid";--> statement-breakpoint
ALTER TABLE "software"."component" DROP CONSTRAINT "software_component_type_valid";--> statement-breakpoint
ALTER TABLE "software"."api" DROP CONSTRAINT "software_api_type_valid";--> statement-breakpoint
ALTER TABLE "software"."template" DROP CONSTRAINT "software_template_type_valid";--> statement-breakpoint
ALTER TABLE "ops"."site" ADD COLUMN "type" text DEFAULT 'production' NOT NULL;--> statement-breakpoint
CREATE INDEX "ops_site_type_idx" ON "ops"."site" USING btree ("type");