import type { Octokit } from "@octokit/rest";
import type {
  GeneratedContent,
  ReleaseContentResult,
} from "@smp/factory-shared/release-content-schema";
import type { GitHostAdapter } from "../../adapters/git-host-adapter";
import { logger } from "../../logger";

/**
 * Publishes generated release content to GitHub as a draft PR.
 *
 * Creates a new branch, commits all generated files via the GitHub Git Data API
 * (no local clone required), and opens a draft PR for review.
 */
export class ReleaseContentPublisher {
  constructor(
    private readonly octokit: Octokit,
    private readonly gitHostAdapter: GitHostAdapter,
  ) {}

  async publish(
    repoFullName: string,
    version: string,
    content: GeneratedContent[],
    baseBranch: string,
  ): Promise<ReleaseContentResult> {
    const [owner, repo] = repoFullName.split("/");
    if (!owner || !repo) {
      throw new Error(`Invalid repo full name: ${repoFullName}`);
    }

    const branchName = `release-content/v${version}`;

    // 1. Get the SHA of the base branch
    const { data: baseRef } = await this.octokit.rest.git.getRef({
      owner,
      repo,
      ref: `heads/${baseBranch}`,
    });
    const baseSha = baseRef.object.sha;

    // 2. Create the branch
    try {
      await this.octokit.rest.git.createRef({
        owner,
        repo,
        ref: `refs/heads/${branchName}`,
        sha: baseSha,
      });
    } catch (err: unknown) {
      // Branch may already exist from a previous run — update it
      const status = (err as { status?: number }).status;
      if (status === 422) {
        await this.octokit.rest.git.updateRef({
          owner,
          repo,
          ref: `heads/${branchName}`,
          sha: baseSha,
          force: true,
        });
      } else {
        throw err;
      }
    }

    // 3. For each generated file, create or update via the Contents API
    for (const file of content) {
      // Check if the file already exists (for changelog, we prepend)
      let existingContent: string | null = null;
      let existingSha: string | null = null;

      try {
        const { data: existing } = await this.octokit.rest.repos.getContent({
          owner,
          repo,
          path: file.filename,
          ref: branchName,
        });
        if ("content" in existing) {
          existingContent = Buffer.from(existing.content, "base64").toString();
          existingSha = existing.sha;
        }
      } catch {
        // File doesn't exist yet
      }

      let finalContent: string;
      if (file.type === "changelog" && existingContent) {
        // Prepend new version entry to existing changelog
        finalContent = prependToChangelog(file.content, existingContent);
      } else {
        finalContent = file.content;
      }

      const params: {
        owner: string;
        repo: string;
        path: string;
        message: string;
        content: string;
        branch: string;
        sha?: string;
      } = {
        owner,
        repo,
        path: file.filename,
        message: `docs(${file.type}): generate ${file.type} for v${version}`,
        content: Buffer.from(finalContent).toString("base64"),
        branch: branchName,
      };

      if (existingSha) {
        params.sha = existingSha;
      }

      await this.octokit.rest.repos.createOrUpdateFileContents(params);

      logger.info(
        { file: file.filename, type: file.type },
        "Published release content file",
      );
    }

    // 4. Create a draft PR
    const fileList = content.map((f) => `- \`${f.filename}\` (${f.type})`).join("\n");
    const pr = await this.gitHostAdapter.createPullRequest(repoFullName, {
      title: `docs: release content for v${version}`,
      body: [
        `## Auto-generated release content for v${version}`,
        "",
        "This PR was automatically generated by the factory release content pipeline.",
        "Please review each file before merging.",
        "",
        "### Generated files",
        fileList,
        "",
        "---",
        "_This content was generated by AI and should be reviewed for accuracy before publishing._",
      ].join("\n"),
      head: branchName,
      base: baseBranch,
      draft: true,
    });

    logger.info(
      { prNumber: pr.number, prUrl: pr.url, version },
      "Created draft PR for release content",
    );

    return {
      prUrl: pr.url,
      prNumber: pr.number,
      generatedFiles: content.map((f) => f.filename),
      version,
    };
  }
}

/**
 * Prepend a new changelog entry after the main heading,
 * preserving the existing content below.
 */
function prependToChangelog(
  newEntry: string,
  existingContent: string,
): string {
  // Find the first ## heading (existing version entry) or end of first heading block
  const lines = existingContent.split("\n");
  let insertIdx = 0;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]!;
    // Skip the main "# Changelog" heading and any description text
    if (line.startsWith("# ")) {
      insertIdx = i + 1;
      // Skip blank lines after the heading
      while (insertIdx < lines.length && lines[insertIdx]!.trim() === "") {
        insertIdx++;
      }
      // If the next line is descriptive text (not a ## heading), skip it too
      while (
        insertIdx < lines.length &&
        !lines[insertIdx]!.startsWith("## ") &&
        lines[insertIdx]!.trim() !== ""
      ) {
        insertIdx++;
      }
      // Skip trailing blank lines
      while (insertIdx < lines.length && lines[insertIdx]!.trim() === "") {
        insertIdx++;
      }
      break;
    }
  }

  // If no heading found, just prepend
  if (insertIdx === 0) {
    return newEntry + "\n" + existingContent;
  }

  const before = lines.slice(0, insertIdx).join("\n");
  const after = lines.slice(insertIdx).join("\n");
  return before + "\n" + newEntry + "\n" + after;
}
