import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join, resolve } from "node:path";
import { stdin as input, stdout as output } from "node:process";
import { createInterface } from "node:readline/promises";

import { ExitCodes } from "@smp/factory-shared/exit-codes";

import type { DxBase } from "../dx-root.js";
import { exitWithError } from "../lib/cli-exit.js";

import { toDxFlags } from "./dx-flags.js";
import { setExamples } from "../plugins/examples-plugin.js";

setExamples("init", [
  "$ dx init                Create docker-compose.yaml interactively",
  "$ dx init --force        Overwrite existing docker-compose.yaml",
]);

async function promptWithDefault(
  label: string,
  defaultValue: string
): Promise<string> {
  if (!input.isTTY) return defaultValue;
  const rl = createInterface({ input, output });
  try {
    const answer = await rl.question(`${label} [${defaultValue}]: `);
    const t = answer.trim();
    return t || defaultValue;
  } finally {
    rl.close();
  }
}

function buildComposeContent(opts: {
  name: string;
  owner: string;
  targetDir: string;
}): string {
  const hasApi = existsSync(join(opts.targetDir, "api"));

  const lines: string[] = [
    "# Docker Compose — generated by dx init",
    "",
    "x-catalog:",
    `  name: ${opts.name}`,
    `  owner: ${opts.owner}`,
    "",
    "services:",
  ];

  if (hasApi) {
    lines.push(
      "  api:",
      "    build:",
      "      context: ./api",
      "      dockerfile: ./api/Dockerfile",
      "    ports:",
      '      - "3000:3000"',
      "    labels:",
      '      catalog.type: service',
      '      catalog.owner: ' + opts.owner,
      '      dx.runtime: node',
    );
  }

  if (lines[lines.length - 1] === "services:") {
    // No services detected, add a placeholder comment
    lines.push("  # Add your services here");
  }

  return lines.join("\n") + "\n";
}

export function initCommand(app: DxBase) {
  return app
    .sub("init")
    .meta({
      description:
        "Create docker-compose.yaml in the current directory (interactive when a TTY)",
    })
    .flags({
      force: {
        type: "boolean",
        short: "f",
        description: "Overwrite existing docker-compose.yaml if it has content",
      },
      dir: {
        type: "string",
        short: "C",
        description: "Directory to write docker-compose.yaml into (default: cwd)",
      },
    })
    .run(async ({ flags }) => {
      const f = toDxFlags(flags);
      const targetDir = (flags.dir as string | undefined)
        ? resolve(process.cwd(), flags.dir as string)
        : process.cwd();
      const composePath = join(targetDir, "docker-compose.yaml");
      const force = Boolean(flags.force);

      try {
        if (existsSync(composePath)) {
          const existing = readFileSync(composePath, "utf8").trim();
          if (existing.length > 0 && !force) {
            exitWithError(
              f,
              `docker-compose.yaml already exists and is not empty (${composePath}).\n` +
                `Use --force to overwrite, or edit the file by hand.`,
              ExitCodes.GENERAL_FAILURE
            );
          }
        }

        const defaultName = basename(targetDir).replace(/[^a-zA-Z0-9_-]/g, "-") || "my-project";
        const projectName = await promptWithDefault("Project name", defaultName);
        const ownerName = await promptWithDefault("Owner/team", "local");

        const content = buildComposeContent({
          name: projectName,
          owner: ownerName,
          targetDir,
        });
        writeFileSync(composePath, content, "utf8");

        if (f.json) {
          console.log(
            JSON.stringify({
              success: true,
              path: composePath,
              name: projectName,
              owner: ownerName,
            })
          );
        } else {
          console.log(`Wrote ${composePath}`);
          console.log(
            "Next: add services with labels, then run `dx up` or `dx dev`."
          );
        }
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        exitWithError(f, msg);
      }
    });
}
