import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join, resolve } from "node:path";
import { stdin as input, stdout as output } from "node:process";
import { createInterface } from "node:readline/promises";

import { ExitCodes } from "@smp/factory-shared/exit-codes";

import type { DxBase } from "../dx-root.js";
import { exitWithError } from "../lib/cli-exit.js";

import { toDxFlags } from "./dx-flags.js";
import { setExamples } from "../plugins/examples-plugin.js";

setExamples("init", [
  "$ dx init                Create dx.yaml interactively",
  "$ dx init --force        Overwrite existing dx.yaml",
]);

async function promptWithDefault(
  label: string,
  defaultValue: string
): Promise<string> {
  if (!input.isTTY) return defaultValue;
  const rl = createInterface({ input, output });
  try {
    const answer = await rl.question(`${label} [${defaultValue}]: `);
    const t = answer.trim();
    return t || defaultValue;
  } finally {
    rl.close();
  }
}

function componentsBlock(targetDir: string): string {
  const hasApi = existsSync(join(targetDir, "api"));
  const hasUi = existsSync(join(targetDir, "ui"));
  if (hasApi && hasUi) {
    return `components:
  api:
    path: api
    port: 3000
  ui:
    path: ui
    port: 3000`;
  }
  if (hasApi) {
    return `components:
  api:
    path: api
    port: 3000`;
  }
  if (hasUi) {
    return `components:
  ui:
    path: ui
    port: 3000`;
  }
  return `components: {}`;
}

function buildDxYamlContent(opts: {
  module: string;
  team: string;
  targetDir: string;
}): string {
  const header =
    "# Software Factory dx.yaml — generated by dx init\n" +
    "# Docs: add components (path, port), optional dependencies and connections.\n";
  const body = [
    `module: ${JSON.stringify(opts.module)}`,
    `team: ${JSON.stringify(opts.team)}`,
    componentsBlock(opts.targetDir),
    "dependencies: {}",
    "connections: {}",
  ].join("\n");
  return `${header}\n${body}\n`;
}

export function initCommand(app: DxBase) {
  return app
    .sub("init")
    .meta({
      description:
        "Create dx.yaml in the current directory (interactive when a TTY)",
    })
    .flags({
      force: {
        type: "boolean",
        short: "f",
        description: "Overwrite existing dx.yaml if it has content",
      },
      dir: {
        type: "string",
        short: "C",
        description: "Directory to write dx.yaml into (default: cwd)",
      },
    })
    .run(async ({ flags }) => {
      const f = toDxFlags(flags);
      const targetDir = (flags.dir as string | undefined)
        ? resolve(process.cwd(), flags.dir as string)
        : process.cwd();
      const dxYamlPath = join(targetDir, "dx.yaml");
      const force = Boolean(flags.force);

      try {
        if (existsSync(dxYamlPath)) {
          const existing = readFileSync(dxYamlPath, "utf8").trim();
          if (existing.length > 0 && !force) {
            exitWithError(
              f,
              `dx.yaml already exists and is not empty (${dxYamlPath}).\n` +
                `Use --force to overwrite, or edit the file by hand.`,
              ExitCodes.GENERAL_FAILURE
            );
          }
        }

        const defaultModule = basename(targetDir).replace(/[^a-zA-Z0-9_-]/g, "-") || "my-module";
        const moduleName = await promptWithDefault("Module name", defaultModule);
        const teamName = await promptWithDefault("Team", "local");

        const content = buildDxYamlContent({
          module: moduleName,
          team: teamName,
          targetDir,
        });
        writeFileSync(dxYamlPath, content, "utf8");

        if (f.json) {
          console.log(
            JSON.stringify({
              success: true,
              path: dxYamlPath,
              module: moduleName,
              team: teamName,
            })
          );
        } else {
          console.log(`Wrote ${dxYamlPath}`);
          console.log(
            "Next: set components (paths and ports), then run `dx dev`."
          );
        }
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        exitWithError(f, msg);
      }
    });
}
