import type { TemplateVars, GeneratedFile } from "./types.js";
import { generate as generateNodeApi } from "./standalone/node-api.js";
import { generate as generateWebApp } from "./standalone/web-app.js";

export function generate(vars: TemplateVars): GeneratedFile[] {
  const { name, owner, description } = vars;
  const desc = description || `${name} platform`;

  const files: GeneratedFile[] = [];

  // ── Root files ──────────────────────────────────────────────────────

  // package.json
  files.push({
    path: "package.json",
    content: JSON.stringify(
      {
        name,
        private: true,
        type: "module",
        packageManager: "pnpm@9.15.4",
        devDependencies: {
          typescript: "^5.9.3",
          prettier: "^3.5.3",
        },
      },
      null,
      2,
    ),
  });

  // pnpm-workspace.yaml
  files.push({
    path: "pnpm-workspace.yaml",
    content: `packages:
  - "packages/npm/*"
  - "services/*"
  - "apps/*"
`,
  });

  // catalog.yaml
  files.push({
    path: "catalog.yaml",
    content: `apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: ${name}
  description: ${desc}
spec:
  owner: ${owner}
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: apps
  description: Frontend applications
spec:
  owner: ${owner}
  domain: ${name}
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: services
  description: Backend microservices
spec:
  owner: ${owner}
  domain: ${name}
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: infra
  description: Infrastructure services
spec:
  owner: ${owner}
  domain: ${name}
`,
  });

  // docker-compose.yaml
  files.push({
    path: "docker-compose.yaml",
    content: `# Docker Compose — generated by dx init
#
# All services and infrastructure are defined in compose/*.yml files.
# This file includes them and is the single entry point for \`dx up\` / \`dx dev\`.

include:
  # Infrastructure
  - path: compose/postgres.yml
  - path: compose/auth.yml
  - path: compose/gateway.yml
  # Services
  - path: compose/${name}-api.yml
  # Apps
  - path: compose/${name}-app.yml
`,
  });

  // .gitignore
  files.push({
    path: ".gitignore",
    content: `# Dependencies
node_modules/

# Build output
dist/
.output/
target/
build/

# Python
__pycache__/
*.pyc
.venv/

# Environment
.env
.env.*
!.env.example

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# dx
.dx/dev/

# Logs
*.log
`,
  });

  // .prettierrc
  files.push({
    path: ".prettierrc",
    content: JSON.stringify(
      { semi: true, singleQuote: false, trailingComma: "all" },
      null,
      2,
    ),
  });

  // ── compose/ directory ──────────────────────────────────────────────

  // compose/postgres.yml
  files.push({
    path: "compose/postgres.yml",
    content: `services:
  infra-postgres:
    image: postgres:16-alpine
    ports:
      - "\${INFRA_POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: \${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: \${POSTGRES_DB:-${name}}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    labels:
      catalog.type: database
      catalog.owner: ${owner}
      catalog.description: "PostgreSQL database"
      catalog.port.5432.name: postgres
      catalog.port.5432.protocol: tcp

volumes:
  postgres-data:
`,
  });

  // compose/auth.yml
  files.push({
    path: "compose/auth.yml",
    content: `services:
  infra-auth:
    image: node:22-alpine
    # TODO: Replace with your auth service image
    ports:
      - "\${INFRA_AUTH_PORT:-8180}:3000"
    depends_on:
      infra-postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://\${POSTGRES_USER:-postgres}:\${POSTGRES_PASSWORD:-postgres}@infra-postgres:5432/\${POSTGRES_DB:-${name}}
    healthcheck:
      test: ["CMD-SHELL", "node -e \\"fetch('http://localhost:3000/api/v1/auth/ok').then(r=>{if(!r.ok)process.exit(1)}).catch(()=>process.exit(1))\\""]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    labels:
      catalog.type: service
      catalog.owner: ${owner}
      catalog.description: "Authentication service"
      catalog.port.3000.name: http
      catalog.port.3000.protocol: http
`,
  });

  // compose/gateway.yml
  files.push({
    path: "compose/gateway.yml",
    content: `services:
  infra-gateway:
    image: apache/apisix:3.11.0-debian
    ports:
      - "\${INFRA_GATEWAY_PORT:-9080}:9080"
    volumes:
      - ./infra/apisix/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9080/apisix/status || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      catalog.type: service
      catalog.owner: ${owner}
      catalog.description: "API gateway"
      catalog.port.9080.name: http
      catalog.port.9080.protocol: http
`,
  });

  // compose/{name}-api.yml
  files.push({
    path: `compose/${name}-api.yml`,
    content: `services:
  ${name}-api:
    build:
      context: ../services/${name}-api
      dockerfile: Dockerfile
    ports:
      - "\${API_PORT:-3000}:3000"
    depends_on:
      infra-postgres:
        condition: service_healthy
      infra-auth:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://\${POSTGRES_USER:-postgres}:\${POSTGRES_PASSWORD:-postgres}@infra-postgres:5432/\${POSTGRES_DB:-${name}}
      AUTH_JWKS_URL: http://infra-auth:3000/api/v1/auth/.well-known/jwks.json
    healthcheck:
      test: ["CMD-SHELL", "node -e \\"fetch('http://localhost:3000/health').then(r=>{if(!r.ok)process.exit(1)}).catch(()=>process.exit(1))\\""]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    labels:
      catalog.type: service
      catalog.owner: ${owner}
      catalog.description: "${name} API"
      catalog.port.3000.name: http
      catalog.port.3000.protocol: http
      dx.runtime: node
`,
  });

  // compose/{name}-app.yml
  files.push({
    path: `compose/${name}-app.yml`,
    content: `services:
  ${name}-app:
    build:
      context: ../apps/${name}-app
      dockerfile: Dockerfile
    ports:
      - "\${APP_PORT:-9000}:3000"
    depends_on:
      ${name}-api:
        condition: service_healthy
    labels:
      catalog.type: website
      catalog.owner: ${owner}
      catalog.description: "${name} frontend"
      catalog.port.3000.name: http
      catalog.port.3000.protocol: http
      dx.runtime: node
`,
  });

  // ── infra/ directory ────────────────────────────────────────────────

  // infra/apisix/config.yaml
  files.push({
    path: "infra/apisix/config.yaml",
    content: `deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml

apisix:
  node_listen: 9080

routes: []
`,
  });

  // infra/auth/auth.settings.yaml
  files.push({
    path: "infra/auth/auth.settings.yaml",
    content: `# Auth service configuration
# See https://www.better-auth.com for documentation
`,
  });

  // ── Starter service: services/{name}-api/ ───────────────────────────

  const apiFiles = generateNodeApi(vars);
  for (const file of apiFiles) {
    // Skip docker-compose.yaml — it lives in compose/ instead
    if (file.path === "docker-compose.yaml") continue;
    files.push({
      path: `services/${name}-api/${file.path}`,
      content: file.content,
    });
  }

  // ── Starter app: apps/{name}-app/ ──────────────────────────────────

  const appFiles = generateWebApp(vars);
  for (const file of appFiles) {
    files.push({
      path: `apps/${name}-app/${file.path}`,
      content: file.content,
    });
  }

  // ── Placeholder directories ─────────────────────────────────────────

  files.push({ path: "packages/npm/.gitkeep", content: "" });
  files.push({ path: "packages/java/.gitkeep", content: "" });
  files.push({ path: "packages/python/.gitkeep", content: "" });
  files.push({ path: "docs/.gitkeep", content: "" });
  files.push({ path: "scripts/.gitkeep", content: "" });

  // ── .dx/ state files ───────────────────────────────────────────────

  files.push({ path: ".dx/ports.json", content: "{}" });
  files.push({ path: ".dx/packages.json", content: "{}" });

  return files;
}
