import {
  cursorRules,
  dxHookFiles,
  dxPackageJsonKey,
  gitattributes,
  githubWorkflow,
  gitignore,
  nodeVersion,
  npmrc,
  prTemplate,
} from "./dx-scaffold.js"
import {
  dxConventionsYaml,
  editorConfig,
  nodeOxlintConfig,
  nodeQualityPackageJson,
  vscodeExtensionsNode,
  vscodeSettingsNode,
} from "./quality-configs.js"
import { generate as generateAuthResource } from "./resource/auth.js"
import { generate as generateGatewayResource } from "./resource/gateway.js"
import { generate as generatePostgresResource } from "./resource/postgres.js"
import { generate as generateNodeApi } from "./standalone/node-api.js"
import { generate as generateWebApp } from "./standalone/web-app.js"
import type { GeneratedFile, TemplateVars } from "./types.js"

export function generate(vars: TemplateVars): GeneratedFile[] {
  const { name, owner, description } = vars
  const desc = description || `${name} platform`

  const files: GeneratedFile[] = []

  // ── Root files ──────────────────────────────────────────────────────

  // package.json — with dx config key
  files.push({
    path: "package.json",
    content: JSON.stringify(
      {
        name,
        private: true,
        type: "module",
        packageManager: "pnpm@9.15.4",
        engines: { node: ">=22" },
        dx: dxPackageJsonKey({ name, owner, type: "monorepo" }),
        scripts: {
          lint: "oxlint .",
          "lint:fix": "oxlint --fix .",
          typecheck: "pnpm -r typecheck",
          test: "pnpm -r test",
          "format:check": "prettier --check .",
          format: "prettier --write .",
        },
        devDependencies: {
          typescript: "^5.9.3",
          prettier: "^3.5.3",
          ...nodeQualityPackageJson().devDependencies,
        },
        "lint-staged": nodeQualityPackageJson()["lint-staged"],
      },
      null,
      2
    ),
  })

  // pnpm-workspace.yaml
  files.push({
    path: "pnpm-workspace.yaml",
    content: `packages:
  - "packages/npm/*"
  - "services/*"
  - "apps/*"
`,
  })

  // docker-compose.yaml (the project catalog — catalog info is derived from labels)
  files.push({
    path: "docker-compose.yaml",
    content: `# Docker Compose — generated by dx init
#
# All services and resources are defined in compose/*.yml files.
# This file includes them and is the single entry point for \`dx up\` / \`dx dev\`.

include:
  # Resources
  - path: compose/postgres.yml
  - path: compose/auth.yml
  - path: compose/gateway.yml
  # Services
  - path: compose/${name}-api.yml
  # Apps
  - path: compose/${name}-app.yml
`,
  })

  // .gitignore (dx-aware)
  files.push(gitignore())

  // .prettierrc
  files.push({
    path: ".prettierrc",
    content: JSON.stringify(
      { semi: true, singleQuote: false, trailingComma: "all" },
      null,
      2
    ),
  })

  // ── compose/ directory ──────────────────────────────────────────────

  // compose/postgres.yml — from resource template
  files.push(...generatePostgresResource({ owner, projectName: name }))

  // compose/auth.yml — from resource template
  files.push(...generateAuthResource({ owner, projectName: name }))

  // compose/gateway.yml — from resource template
  files.push(...generateGatewayResource({ owner, projectName: name }))

  // compose/{name}-api.yml
  files.push({
    path: `compose/${name}-api.yml`,
    content: `services:
  ${name}-api:
    build:
      context: ../services/${name}-api
      dockerfile: Dockerfile
    ports:
      - "\${API_PORT:-3000}:3000"
    depends_on:
      infra-postgres:
        condition: service_healthy
      infra-auth:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://\${POSTGRES_USER:-postgres}:\${POSTGRES_PASSWORD:-postgres}@infra-postgres:5432/\${POSTGRES_DB:-${name}}
      AUTH_JWKS_URL: http://infra-auth:3000/api/v1/auth/.well-known/jwks.json
    healthcheck:
      test: ["CMD-SHELL", "node -e \\"fetch('http://localhost:3000/health').then(r=>{if(!r.ok)process.exit(1)}).catch(()=>process.exit(1))\\""]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    labels:
      dx.type: service
      dx.owner: ${owner}
      dx.description: "${name} API"
      dx.port.3000.name: http
      dx.port.3000.protocol: http
      dx.runtime: node
`,
  })

  // compose/{name}-app.yml
  files.push({
    path: `compose/${name}-app.yml`,
    content: `services:
  ${name}-app:
    build:
      context: ../apps/${name}-app
      dockerfile: Dockerfile
    ports:
      - "\${APP_PORT:-9000}:3000"
    depends_on:
      ${name}-api:
        condition: service_healthy
    labels:
      dx.type: website
      dx.owner: ${owner}
      dx.description: "${name} frontend"
      dx.port.3000.name: http
      dx.port.3000.protocol: http
      dx.runtime: node
`,
  })

  // ── Starter service: services/{name}-api/ ───────────────────────────

  const apiFiles = generateNodeApi(vars)
  for (const file of apiFiles) {
    // Skip docker-compose.yaml — it lives in compose/ instead
    if (file.path === "docker-compose.yaml") continue
    files.push({
      path: `services/${name}-api/${file.path}`,
      content: file.content,
    })
  }

  // ── Starter app: apps/{name}-app/ ──────────────────────────────────

  const appFiles = generateWebApp(vars)
  for (const file of appFiles) {
    files.push({
      path: `apps/${name}-app/${file.path}`,
      content: file.content,
    })
  }

  // ── Quality tooling + conventions ──────────────────────────────────

  files.push(nodeOxlintConfig())
  files.push(editorConfig())
  files.push(vscodeExtensionsNode())
  files.push(vscodeSettingsNode())
  files.push(dxConventionsYaml(owner))

  // ── Placeholder directories ─────────────────────────────────────────

  files.push({ path: "packages/npm/.gitkeep", content: "" })
  files.push({ path: "packages/java/.gitkeep", content: "" })
  files.push({ path: "packages/python/.gitkeep", content: "" })
  files.push({ path: "docs/.gitkeep", content: "" })
  files.push({ path: "scripts/.gitkeep", content: "" })

  // ── dx scaffold files ──────────────────────────────────────────────

  // .dx/hooks/ — git hook scripts (commit-msg, pre-commit, pre-push, etc.)
  files.push(...dxHookFiles())

  // .dx/ state files
  files.push({ path: ".dx/ports.json", content: "{}" })
  files.push({ path: ".dx/packages.json", content: "{}" })

  // .gitattributes — line endings, binary detection
  files.push(gitattributes())

  // .github/ — CI workflow and PR template
  files.push(githubWorkflow())
  files.push(prTemplate())

  // .cursor/rules — AI agent context
  files.push(cursorRules(name))

  // .npmrc — registry defaults
  files.push(npmrc())

  // .node-version — Node version for fnm
  files.push(nodeVersion())

  return files
}
